server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: backend-user
            uri: http://k8s-backend-user-service.default.svc.cluster.local:8080
            predicates:
              - Path=/api/user/**
